maddipaddi/Fireside-Holidaze

- .husky/pre-commit
- eslint.config.js
- eslint.config.mjs
- package-lock.json
- package.json
- src/App.jsx
- src/main.jsx
- vite.config.js
This PR will:
- install and configure Prettier for consistent formatting of the project
- install and configure eslint-config-prettier to make ESLint and Prettier play nice with each other
- install and configure Husky for pre-commit hooks, aka. running Prettier formatting on staged files before committing
Closes #54
> 54 configure project with tools

- package-lock.json
- package.json
- src/App.jsx
- src/pages/Home.jsx
- src/pages/Listings.jsx
- src/pages/Login.jsx
- src/pages/Register.jsx
Installed React-Router-Dom 
Set up Routs for pages on App.jsx
Added pages and added them to routes
> 10 add react router

- package-lock.json
- package.json
- src/components/layout/Header.jsx
This PR will do the following to the Header component:
- add basic styling
- implement mobile hamburger menu functionality
The styling is only half-way done, submitting PR now to access Veronika's changes where she implements colors and fonts from style guide.
> 16 style header component

- src/components/layout/CategoryItem.jsx
- src/pages/Home.jsx
> 39 add elements to homepage

- src/App.jsx
- src/Constants.mjs
- src/components/VenueCards.jsx
- src/pages/Venues.jsx
- Added venue cards
- Added fetch call for all venues (no params)
-Added constants.mjs
> 18 render list of venues

- src/components/layout/Layout.jsx
- src/hooks/useApiRequest.mjs
- src/pages/Home.jsx
- src/pages/Register.jsx
- src/utils/api.mjs
- src/utils/errorHandler.mjs
- src/utils/successMessage.mjs
This PR will:
- add registration functionality
- create apiRequest utility function and hook
- create error and success utility functions (will need improvement and UI facing functionality later)
Note: no styling was added, it looks atrocious, but it is functional :)
> 21 create registration functionality

- src/Constants.mjs
- src/pages/Register.jsx
- src/pages/Venues.jsx
- src/utils/constants.mjs
This PR adds a venue manager as an option when registering.
Closes #48
> 48 add venue manager option to registration

- src/components/Searchbar.jsx
- src/pages/Register.jsx
Add styling to register form
Closes #52
> style: add cohesive look to form + add redirect

- src/App.jsx
- src/components/layout/Header.jsx
- src/pages/Login.jsx
- src/pages/Profile.jsx
- src/utils/auth.mjs
This PR will:
- add profile page to router
- add auth helper functions (get current user and logging out)
- add login functionality (repurposed styling from register form)
- add UI changes to navbar according to log in state -> when logged out: "register" "log in" - when logged in: "log out" "profile img"
> 23 create loginlogout functionality

- src/pages/About.jsx
> feat: add about me section and contact form

- src/pages/Terms.jsx
> feat: add content and styling to terms

- package-lock.json
- package.json
- src/components/layout/Footer.jsx
- src/index.css
Add functional light/darkmode, with switch(button) in footer.
Closes #62
> 62 lightdarkmode

- src/components/VenueCards.jsx
- src/pages/Venues.jsx
This PR adds styling to "all venues" page. Dark mode will need to be fixed in a separate issue.
> feat: style all venues page

- src/App.jsx
- src/components/VenueCards.jsx
- src/pages/SingleVenues.jsx
- src/utils/constants.mjs
Fixed merging issue. 
Will now dynamically display single venue page
> 72 single venue page with id fix

- src/components/ProfileVenues.jsx
- src/components/VenueCards.jsx
- src/pages/Profile.jsx
- src/utils/constants.mjs
This PR makes it so venue managers can see their own venues on their profile page and access editing and deletion. 
Edit and delete logic must still be added. Functionality that changes profile page based on customer/venue manager access must still be added.
> feat: display venue manager's venues on their profile page

- src/App.jsx
- src/components/AddVenue.jsx
- src/components/VenueCards.jsx
- src/pages/UpdateVenue.jsx
This PR will add update venue functionality :)
> 8 update venue functionality

- src/components/AddVenue.jsx
- src/components/ProfileVenues.jsx
- src/components/UserContext.jsx
- src/components/layout/Header.jsx
- src/main.jsx
- src/pages/Login.jsx
- src/pages/Profile.jsx
- src/utils/auth.mjs
- src/utils/constants.mjs
- src/utils/fetchUserProfile.mjs
- src/utils/updateProfile.mjs
> Update user profile

- package-lock.json
- package.json
- src/components/Carousel.jsx
- src/pages/Home.jsx
> 40 add popular destionations

- src/App.jsx
- src/components/Carousel.jsx
- src/components/Searchbar.jsx
- src/components/VenueContext.jsx
- src/main.jsx
- src/pages/SearchResults.jsx
- src/pages/Venues.jsx
> 36 functionality searchbar

- src/components/Calender.jsx
- src/pages/SingleVenues.jsx
- src/utils/constants.mjs
Adds calendar component to single page venue
Still needs fixes to the fetch function. ( auth issues that needs to get looked into - api.mjs)
will need to wait to see when we can add fromDate and toDate. so we can test displey of time booked.
> 22 create calendar component 2

- src/components/DeleteVenues.jsx
- src/components/ProfileVenues.jsx
- src/utils/api.mjs
Let the user delete a venue they have created
Closes #7
> 7 create delete venue functionality

- src/components/BookingCard.jsx
- src/pages/SingleVenues.jsx
Adds Booking functionality
Displays price depending on to and from date
(Still needs to fix it so that it only can select dates that are available)
> 24 create customer booking functionality

- src/components/BookingCard.jsx
No merge conflicts detected after all. Just cleaned up console logs and changed NOK to $ for consistency :)
> chore: remove console logs and change NOK to $ for consistency

- src/components/UpcomingBookings.jsx
- src/components/VenueManBookings.jsx
- src/pages/Profile.jsx
This PR:
- makes it so a venue manager can see upcoming and past bookings for venues they manage (sorted by date)
- implements temporary basic design, there will be a separate issue where a proper design is implemented
> 6 create venue manager booking functionality

- src/components/Calender.jsx
Issue with not seeing first day of booked venue date is fixed.
> feat: fix display of dates booked

- src/components/BookingCard.jsx
Added logic to avoid double booking
> Feat: add logic to avoid duble booking

- src/components/BookingCard.jsx
- src/components/Calender.jsx
This commit will add explanation to color use, shown under the calendar. It also has responsiveness
> 101 add color codes to explain if the date are free or taken on the calendar

- src/pages/Login.jsx
This PR resolves venue manager view that doesn't show up when first logging in. 
The issue was that the "venueManager: boolean" does not get returned automatically with user info when logging in. 
Therefore I have added fetching the full profile data to the log in function :)
> fix: resolve broken venue manager view on first log in

- src/components/VenueManBookings.jsx
- src/pages/Venues.jsx
Add styling to upcoming and past bookings for venue managers.
Closes #98
> 98 design upcomingpast bookings for venue managers

- src/App.jsx
- src/components/layout/Header.jsx
- src/pages/Categories.jsx
- src/pages/Home.jsx
This PR will filter venues by categories depending of the mention of "forest", "sea" or "mountain" in either the title or description :) 
It maintains the filtering of Fireside Holidaze with the app specific phrase.
> feat: filter venues by categories on their respective category pages

- src/components/Carousel.jsx
- src/components/ProfileVenues.jsx
- src/components/VenueGrid.jsx
- src/components/VenueManBookings.jsx
- src/pages/SingleVenues.jsx
- src/pages/UpdateVenue.jsx
- src/pages/Venues.jsx
> 107 create better placeholders for empty content

- src/components/CustomerBookings.jsx
- src/pages/Profile.jsx
This PR makes it so customers can see their upcoming and past bookings :)
> feat: display bookings made by customer on their profile page

- src/components/Calender.jsx
- src/pages/Categories.jsx
- src/pages/Home.jsx
- src/pages/SearchResults.jsx
Add cohesive design as empty placeholders to loading screens
Closes #106
> 106 implement proper UI for loading screens

- src/components/BookingCard.jsx
- src/components/Calender.jsx
Fixed buttons to work for both light and dark mode
> 117 fix button style for booking section on single post page

- src/components/CategoryItem.jsx
- src/pages/Home.jsx
Fixed issue with increased loading times on button "View all locations" and category images to their respective pages compared to using navbar. 
- Replaced anchor tags with React Router's <Link> to enable client-side navigation,
prevent full page reloads, and improve performance across category links.
Closes #124
> 124 debug increased loading times

- src/components/BookingCard.jsx
- src/components/Calender.jsx
- src/components/Searchbar.jsx
- src/pages/SearchResults.jsx
- src/pages/SingleVenues.jsx
- src/utils/fetchAllVenues.mjs
This PR: 
- Cojoins calendar and booking component to work together (small issue with being able to select dates over booked dates - fix in separate issue)
- Improves search functionality with date and guest filtering (on a general level when searching locations - create separate issue for searching specific venues)
> 122 try to improve search functionality

- src/components/CategoryItem.jsx
- src/components/CustomerBookings.jsx
- src/components/DeleteVenues.jsx
- src/components/VenueManBookings.jsx
- src/pages/Profile.jsx
- src/pages/Terms.jsx
- src/utils/errorHandler.mjs
- src/utils/showConfirmDialog.mjs
- src/utils/successMessage.mjs
Add confirm, success and error messages across the website
Closes #105
> 105 implement proper UI for successerror messages

- src/pages/Login.jsx
- src/pages/Register.jsx
- src/utils/constants.mjs
- Automatic logged in after register
- Redrirect after log in to homepage
Closes #128
> 128 register

- src/components/AddVenue.jsx
- src/components/Calender.jsx
- src/components/CustomerBookings.jsx
- src/components/DeleteBookings.jsx
- src/components/EditBooking.jsx
- src/components/Searchbar.jsx
- src/components/layout/Header.jsx
- src/pages/Categories.jsx
- src/pages/Login.jsx
- src/pages/Privacy.jsx
- src/pages/Profile.jsx
- src/pages/Register.jsx
- src/pages/SingleVenues.jsx
- src/pages/UpdateVenue.jsx
This PR will: 
- make small adjustments to styling, mainly revolving around spacing
- make mobile nav close when navigating and clicking outside it
- make edit and delete buttons available on upcoming bookings (but not past)
- add delete booking functionality for customers
- enable customers to edit their bookings
- add the success and error popups for changing booking api request
> 136 add updatedelete functionality to customer bookings

- src/pages/SearchResults.jsx
> feat: make search results look more uniform

- src/components/Calender.jsx
> 145 update js docs for calendar page due to added functionality and handels

- src/components/EditBooking.jsx
- src/index.css
Adds scrollbar to pop up with sticky pop up footer for mobile responsiveness ^^
> feat: make change booking pop up responsive for mobile

- src/components/Carousel.jsx
- src/components/CustomerBookings.jsx
- src/components/ProfileVenues.jsx
- src/components/Searchbar.jsx
- src/components/VenueGrid.jsx
- src/components/VenueManBookings.jsx
- src/components/layout/Header.jsx
- src/pages/Home.jsx
- src/pages/Login.jsx
- src/pages/Profile.jsx
- src/pages/Register.jsx
This PR implements improvements flagged by Wave's chrome extension tool for accessibility. 
I have mostly improved form labelling and controls, opening and closing of menus, and heading hierarchies. 
I have ignored contrast errors flagged in footer, because it seemed to be an error with the wave tool that mixes the light and dark version of the footer in a weird way. I have also ignored the alert of a weird alt text in the profile img (I think it flags it just because it changes dynamically depending on who's logged in).
> 150 run accessibility checks

- src/components/AddVenue.jsx
- src/components/BookingCard.jsx
- src/components/EditBooking.jsx
- src/components/Searchbar.jsx
- src/components/VenueManBookings.jsx
- src/index.css
- src/pages/About.jsx
- src/pages/Home.jsx
- src/pages/Login.jsx
- src/pages/Profile.jsx
- src/pages/Register.jsx
- src/pages/UpdateVenue.jsx
> 154 small changes to design

- src/components/Calender.jsx
- src/components/DeleteBookings.jsx
- src/components/DeleteVenues.jsx
- src/components/ProfileVenues.jsx
- src/components/context/VenueContext.jsx
- src/pages/About.jsx
- src/pages/SingleVenues.jsx
- src/pages/UpdateVenue.jsx
Deleted all consol.log. Changed consol.error to handleError(error)
> feat: delete consol.log and changed error log to handleError(error)

- src/components/ProfileVenues.jsx
Add the ability for venue managers to view their own venues, in addition to editing and deleting them.
Closes #156
> feat: add view venue on venue managers venues

- index.html
- src/App.jsx
- src/components/DynamicFlavicon.jsx
- src/components/layout/Footer.jsx
- src/pages/SingleVenues.jsx
> 164 fix responsivness

- src/pages/Profile.jsx
Bringing the design on profilepage back again 🖌️
> feat: add back design

- src/components/AddVenue.jsx
- src/components/CustomerBookings.jsx
- src/components/DeleteBookings.jsx
- src/components/DynamicFlavicon.jsx
- src/pages/SearchResults.jsx
- Add cursor pointer
- Small changes to colors
- Add "view venue" on customers bookings
Closes #171
> 171 add view venue for customers
